<!DOCTYPE html>
<html>
<head>
    <title>自我介绍</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        :root {
            --apple-blue: #0071e3;
            --apple-gray: #f5f5f7;
            --apple-dark: #1d1d1f;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            color: var(--apple-dark);
            line-height: 1.6;
            margin: 0;
            padding: 0;
            min-height: 100vh;
            background: linear-gradient(135deg, #a8edea 0%, #fed6e3 100%);
            position: relative;
            overflow-x: hidden;
        }
        body::before {
            content: '';
            position: absolute;
            top: -50px;
            left: -50px;
            right: -50px;
            bottom: -50px;
            background: inherit;
            filter: blur(30px);
            z-index: -1;
        }
        .container {
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
        }
        .card {
            background: rgba(255, 255, 255, 0.7);
            backdrop-filter: blur(10px);
            -webkit-backdrop-filter: blur(10px);
            border-radius: 18px;
            padding: 30px;
            margin-bottom: 20px;
            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
            border: 1px solid rgba(255, 255, 255, 0.2);
        }
        h1 {
            color: var(--apple-dark);
            font-size: 32px;
            font-weight: 600;
            margin-top: 0;
        }
        h2 {
            color: var(--apple-blue);
            font-size: 24px;
            font-weight: 500;
            margin-top: 0;
        }
        .contact-button {
            display: inline-block;
            background: var(--apple-blue);
            color: white;
            padding: 12px 24px;
            border-radius: 12px;
            text-decoration: none;
            font-weight: 500;
            margin-top: 10px;
            transition: all 0.3s;
            border: none;
            cursor: pointer;
        }
        .contact-button:hover {
            background: #0077ed;
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0, 113, 227, 0.3);
        }
        .info-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px;
        }
        .tag {
            display: inline-block;
            background: rgba(0, 113, 227, 0.1);
            color: var(--apple-blue);
            padding: 4px 12px;
            border-radius: 6px;
            margin-right: 8px;
            margin-bottom: 8px;
            font-size: 14px;
        }
        @media (max-width: 600px) {
            .info-grid {
                grid-template-columns: 1fr;
            }
            .card {
                padding: 20px;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="card" style="text-align: center;">
            <h1>我</h1>
            <p style="font-size: 18px; color: #86868b;">“张鑫，十八岁，独立行走，能吃能拉，未来可期”</p>
        </div>
        
        <div class="card">
            <h2>基本信息</h2>
            <div class="info-grid">
                <div>
                    <p><strong>姓名：</strong>张鑫</p>
                    <p><strong>年龄：</strong>18</p>
                    <p><strong>专业：</strong>数字经济</p>
                </div>
                <div>
                    <p><strong>学校：</strong>南京大学</p>
                    <p><strong>所在地：</strong>苏州</p>
                    <p><strong>MBTI：</strong>ENTJ</p>
                </div>
            </div>
        </div>
        
        <div class="card">
            <h2>个人简介</h2>
            <p>工科&商科学生，创业者，完美主义者，理想主义者，社交达人，各类新鲜事物的爱好者，科技爱好者，自信者，自负者，眼高手低者，懒人。</p>
            <p>活着，就是为了改变世界。</p>
            
            <div style="margin-top: 20px;">
                <span class="tag">创业</span>
                <span class="tag">科技</span>
                <span class="tag">商业</span>
                <span class="tag">社交</span>
            </div>
        </div>
        
        <div class="card">
            <h2>技能专长</h2>
            <div class="info-grid">
                <div>
                    <p><strong>设计工具：</strong></p>
                    <ul style="list-style-type: none; padding-left: 0;">
                        <li>• Figma</li>
                        <li>• Sketch</li>
                        <li>• Adobe XD</li>
                    </ul>
                </div>
                <div>
                    <p><strong>开发技术：</strong></p>
                    <ul style="list-style-type: none; padding-left: 0;">
                        <li>• HTML/CSS/JavaScript</li>
                        <li>• React/Vue</li>
                        <li>• SwiftUI</li>
                    </ul>
                </div>
            </div>
        </div>
        
        <div class="card" style="text-align: center;">
            <h2>保持联系</h2>
            <p style="margin-bottom: 20px;">期待与您交流合作机会</p>
            <a href="mailto:example@email.com" class="contact-button">发送邮件</a>
            <div style="margin-top: 20px;">
                <a href="#" style="color: var(--apple-blue); margin: 0 10px;">QQ</a>
                <a href="#" style="color: var(--apple-blue); margin: 0 10px;">GitHub</a>
                <a href="#" style="color: var(--apple-blue); margin: 0 10px;">WeChat</a>
            </div>
        </div>
    </div>
</body>
</html>
